name: Publish 🚀

on: 
  workflow_dispatch:
  push:
    branches:
    - main

env:
  WEBAPP_NAME: base-project
  WEBAPP_PACKAGE_PATH: "./publish"
  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./SignalR.sln

    - name: Build
      run: dotnet build ./SignalR.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./SignalR.sln --configuration Release --no-build --output '${{ env.WEBAPP_PACKAGE_PATH }}'

    - name: Deployment
      uses: actions/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.SMARTER_PUBLISH_PROFILE }}
        package: "${{ env.WEBAPP_PACKAGE_PATH }}"
        
        

